[package]
name = "ampdeck"
version = "0.1.0"
authors = ["jesse"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
reqwest = { version = "0.11", features = ["json"] }
rodio = "0.17.3"
tokio = { version = "1", features = ["full"] }

